# Generated by Django 3.1.5 on 2021-01-29 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0002_message_date_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='masa',
            field=models.CharField(choices=[('JOSEF', 'JOSEF'), ('MAKS', 'MAKS')], default=('JOSEF', 'JOSEF'), max_length=5),
        ),
    ]
