# Generated by Django 3.1.5 on 2021-01-29 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0003_message_masa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='masa',
        ),
        migrations.AddField(
            model_name='message',
            name='recipient',
            field=models.CharField(choices=[('elmatador', 'elmatador'), ('safsfsfas', 'safsfsfas'), ('Pepibeats', 'Pepibeats'), ('pokfspoqo', 'pokfspoqo')], default=('safsfsfas', 'safsfsfas'), max_length=100),
        ),
    ]
