# Generated by Django 3.1.5 on 2021-01-29 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0006_conversation_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='title',
        ),
    ]
