# Generated by Django 3.1.5 on 2021-01-31 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0008_participator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participator',
            name='conversation',
        ),
        migrations.AddField(
            model_name='participator',
            name='conversations',
            field=models.ManyToManyField(to='messenger.Conversation'),
        ),
    ]
