# Generated by Django 3.1.5 on 2021-01-27 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_market', '0013_delete_projectmember'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='birthday',
        ),
        migrations.AddField(
            model_name='user',
            name='projects',
            field=models.ManyToManyField(to='project_market.Project'),
        ),
    ]
