# Generated by Django 3.1.5 on 2021-01-27 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210127_1923'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
