# Generated by Django 3.1.5 on 2021-01-26 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_market', '0006_auto_20210126_1022'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='description',
            new_name='short_description',
        ),
    ]
