# Generated by Django 3.1.5 on 2021-01-26 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_market', '0007_auto_20210126_1208'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('rating', models.CharField(choices=[('MR', 'Mr.'), ('MRS', 'Mrs.'), ('MS', 'Ms.')], max_length=3)),
            ],
        ),
    ]
