# Generated by Django 3.1.5 on 2021-01-26 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_market', '0008_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='parent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='project_market.project'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.CharField(choices=[('AWFUL', '★☆☆☆☆'), ('BAD', '★★☆☆☆'), ('OKAY', '★★★☆☆'), ('GOOD', '★★★★☆'), ('AMAZING', '★★★★★')], max_length=7),
        ),
    ]
