# Generated by Django 3.1.5 on 2021-01-27 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_market', '0012_projectmember'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectMember',
        ),
    ]
